set export

DATABASE_URL := "postgresql://postgres:pass@host.docker.internal:5432/db"

run-dev: migrate
    #!/bin/zsh

    bun dev

migrate: install-node-modules
    #!/bin/zsh

    bun migrate

bootstrap: migrate

[private]
install-node-modules:
    #!/bin/zsh

    bun i
